// <auto-generated />
namespace Dentist.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class doctormodelupdate : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(doctormodelupdate));
        
        string IMigrationMetadata.Id
        {
            get { return "201508030926534_doctor model update"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
